book-www: go run github.com/cespare/reflex -s -- sh -c 'cd book-www && go run .'
book-backend: go run github.com/cespare/reflex -s -- sh -c 'cd book-backend && go run .'
book-worker: go run github.com/cespare/reflex -s -- sh -c 'cd book-worker && go run .'
redis: redis-server --save "" --appendonly no
cockroach: ./db/cockroach.bash
