// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	book.proto

It has these top-level messages:
	AddBookRequest
	AddBookResponse
	GetBookRequest
	GetBookResponse
	ListBooksRequest
	ListBooksResponse
	Book
	BookStats
	BookReview
	Job
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job_Type int32

const (
	Job_DOWNLOAD        Job_Type = 0
	Job_CALCULATE_STATS Job_Type = 1
	Job_GET_REVIEWS     Job_Type = 2
)

var Job_Type_name = map[int32]string{
	0: "DOWNLOAD",
	1: "CALCULATE_STATS",
	2: "GET_REVIEWS",
}
var Job_Type_value = map[string]int32{
	"DOWNLOAD":        0,
	"CALCULATE_STATS": 1,
	"GET_REVIEWS":     2,
}

func (x Job_Type) String() string {
	return proto.EnumName(Job_Type_name, int32(x))
}
func (Job_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

type AddBookRequest struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *AddBookRequest) Reset()                    { *m = AddBookRequest{} }
func (m *AddBookRequest) String() string            { return proto.CompactTextString(m) }
func (*AddBookRequest) ProtoMessage()               {}
func (*AddBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddBookRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AddBookResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *AddBookResponse) Reset()                    { *m = AddBookResponse{} }
func (m *AddBookResponse) String() string            { return proto.CompactTextString(m) }
func (*AddBookResponse) ProtoMessage()               {}
func (*AddBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddBookResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetBookRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetBookRequest) Reset()                    { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()               {}
func (*GetBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetBookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetBookResponse struct {
	Book      *Book         `protobuf:"bytes,1,opt,name=book" json:"book,omitempty"`
	Stats     *BookStats    `protobuf:"bytes,2,opt,name=stats" json:"stats,omitempty"`
	Reviews   []*BookReview `protobuf:"bytes,3,rep,name=reviews" json:"reviews,omitempty"`
	JobStatus []string      `protobuf:"bytes,4,rep,name=job_status,json=jobStatus" json:"job_status,omitempty"`
}

func (m *GetBookResponse) Reset()                    { *m = GetBookResponse{} }
func (m *GetBookResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBookResponse) ProtoMessage()               {}
func (*GetBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *GetBookResponse) GetStats() *BookStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *GetBookResponse) GetReviews() []*BookReview {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func (m *GetBookResponse) GetJobStatus() []string {
	if m != nil {
		return m.JobStatus
	}
	return nil
}

type ListBooksRequest struct {
}

func (m *ListBooksRequest) Reset()                    { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string            { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()               {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListBooksResponse struct {
	Books []*Book `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
}

func (m *ListBooksResponse) Reset()                    { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string            { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()               {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type Book struct {
	Id    int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Url   string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
}

func (m *Book) Reset()                    { *m = Book{} }
func (m *Book) String() string            { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()               {}
func (*Book) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type BookStats struct {
	NumberOfWords int64  `protobuf:"varint,1,opt,name=number_of_words,json=numberOfWords" json:"number_of_words,omitempty"`
	LongestWord   string `protobuf:"bytes,2,opt,name=longest_word,json=longestWord" json:"longest_word,omitempty"`
}

func (m *BookStats) Reset()                    { *m = BookStats{} }
func (m *BookStats) String() string            { return proto.CompactTextString(m) }
func (*BookStats) ProtoMessage()               {}
func (*BookStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BookStats) GetNumberOfWords() int64 {
	if m != nil {
		return m.NumberOfWords
	}
	return 0
}

func (m *BookStats) GetLongestWord() string {
	if m != nil {
		return m.LongestWord
	}
	return ""
}

type BookReview struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Review   string `protobuf:"bytes,2,opt,name=review" json:"review,omitempty"`
}

func (m *BookReview) Reset()                    { *m = BookReview{} }
func (m *BookReview) String() string            { return proto.CompactTextString(m) }
func (*BookReview) ProtoMessage()               {}
func (*BookReview) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BookReview) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *BookReview) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

type Job struct {
	Metadata map[string]string `protobuf:"bytes,1,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type     Job_Type          `protobuf:"varint,2,opt,name=type,enum=Job_Type" json:"type,omitempty"`
	Book     *Book             `protobuf:"bytes,3,opt,name=book" json:"book,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Job) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Job) GetType() Job_Type {
	if m != nil {
		return m.Type
	}
	return Job_DOWNLOAD
}

func (m *Job) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func init() {
	proto.RegisterType((*AddBookRequest)(nil), "AddBookRequest")
	proto.RegisterType((*AddBookResponse)(nil), "AddBookResponse")
	proto.RegisterType((*GetBookRequest)(nil), "GetBookRequest")
	proto.RegisterType((*GetBookResponse)(nil), "GetBookResponse")
	proto.RegisterType((*ListBooksRequest)(nil), "ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "ListBooksResponse")
	proto.RegisterType((*Book)(nil), "Book")
	proto.RegisterType((*BookStats)(nil), "BookStats")
	proto.RegisterType((*BookReview)(nil), "BookReview")
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterEnum("Job_Type", Job_Type_name, Job_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BookBackend service

type BookBackendClient interface {
	AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error)
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error)
}

type bookBackendClient struct {
	cc *grpc.ClientConn
}

func NewBookBackendClient(cc *grpc.ClientConn) BookBackendClient {
	return &bookBackendClient{cc}
}

func (c *bookBackendClient) AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error) {
	out := new(AddBookResponse)
	err := grpc.Invoke(ctx, "/BookBackend/AddBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookBackendClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error) {
	out := new(GetBookResponse)
	err := grpc.Invoke(ctx, "/BookBackend/GetBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookBackendClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksResponse, error) {
	out := new(ListBooksResponse)
	err := grpc.Invoke(ctx, "/BookBackend/ListBooks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookBackend service

type BookBackendServer interface {
	AddBook(context.Context, *AddBookRequest) (*AddBookResponse, error)
	GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error)
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksResponse, error)
}

func RegisterBookBackendServer(s *grpc.Server, srv BookBackendServer) {
	s.RegisterService(&_BookBackend_serviceDesc, srv)
}

func _BookBackend_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookBackendServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookBackend/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookBackendServer).AddBook(ctx, req.(*AddBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookBackend_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookBackendServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookBackend/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookBackendServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookBackend_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookBackendServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookBackend/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookBackendServer).ListBooks(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookBackend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BookBackend",
	HandlerType: (*BookBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBook",
			Handler:    _BookBackend_AddBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookBackend_GetBook_Handler,
		},
		{
			MethodName: "ListBooks",
			Handler:    _BookBackend_ListBooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}

func init() { proto.RegisterFile("book.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x1f, 0xdd, 0x9a, 0x9b, 0xad, 0xc9, 0x2e, 0x08, 0x95, 0xa2, 0x49, 0x5d, 0x24, 0x50,
	0x1f, 0x26, 0x0b, 0x95, 0x17, 0x34, 0x24, 0x44, 0xbb, 0x55, 0x13, 0x53, 0xa1, 0x52, 0x5a, 0x56,
	0x89, 0x97, 0x2a, 0x21, 0x1e, 0xea, 0xda, 0xc6, 0x25, 0x76, 0x36, 0xf5, 0x7f, 0xf0, 0xca, 0xff,
	0xe3, 0x67, 0x20, 0x3b, 0x6e, 0xb6, 0x66, 0x6f, 0xb9, 0xe7, 0x9e, 0x5c, 0x1f, 0x1f, 0x9f, 0x0b,
	0x10, 0x33, 0xb6, 0x20, 0xeb, 0x8c, 0x09, 0x16, 0x04, 0xd0, 0xe8, 0x25, 0x49, 0x9f, 0xb1, 0x45,
	0x48, 0x7f, 0xe7, 0x94, 0x0b, 0xf4, 0xc1, 0xca, 0xb3, 0x65, 0xd3, 0x68, 0x1b, 0x1d, 0x27, 0x94,
	0x9f, 0xc1, 0x09, 0x78, 0x25, 0x87, 0xaf, 0x59, 0xca, 0x29, 0x36, 0xc0, 0x9c, 0x27, 0x8a, 0x63,
	0x85, 0xe6, 0x3c, 0x09, 0xda, 0xd0, 0xb8, 0xa4, 0xe2, 0xf1, 0x98, 0x2a, 0xe3, 0x8f, 0x01, 0x5e,
	0x49, 0xd1, 0x53, 0x5e, 0x81, 0x2d, 0xa5, 0x28, 0x96, 0xdb, 0xad, 0x11, 0xd5, 0x54, 0x10, 0xb6,
	0xa1, 0xc6, 0x45, 0x24, 0x78, 0xd3, 0x54, 0x3d, 0x50, 0xbd, 0xb1, 0x44, 0xc2, 0xa2, 0x81, 0x6f,
	0x60, 0x3f, 0xa3, 0x77, 0x73, 0x7a, 0xcf, 0x9b, 0x56, 0xdb, 0xea, 0xb8, 0x5d, 0xb7, 0xf8, 0x5f,
	0x61, 0xe1, 0xb6, 0x87, 0xc7, 0x00, 0xb7, 0x2c, 0x9e, 0xc9, 0x7f, 0x72, 0xde, 0xb4, 0xdb, 0x56,
	0xc7, 0x09, 0x9d, 0x5b, 0x16, 0x8f, 0x15, 0x10, 0x20, 0xf8, 0xc3, 0x39, 0x57, 0xb2, 0xb8, 0x96,
	0x1e, 0xbc, 0x83, 0xa3, 0x47, 0x98, 0xd6, 0xfa, 0x1a, 0x6a, 0x52, 0x18, 0x6f, 0x1a, 0xea, 0x30,
	0x2d, 0xb6, 0xc0, 0x82, 0x4f, 0x60, 0xcb, 0xb2, 0x7a, 0x69, 0x7c, 0x01, 0x35, 0x31, 0x17, 0x4b,
	0xaa, 0x6e, 0xe1, 0x84, 0x45, 0xb1, 0x75, 0xd8, 0x7a, 0x70, 0xf8, 0x1a, 0x9c, 0xf2, 0x7e, 0xf8,
	0x16, 0xbc, 0x34, 0x5f, 0xc5, 0x34, 0x9b, 0xb1, 0x9b, 0xd9, 0x3d, 0xcb, 0x12, 0xae, 0x27, 0x1e,
	0x16, 0xf0, 0xe8, 0x66, 0x2a, 0x41, 0x3c, 0x81, 0x83, 0x25, 0x4b, 0x7f, 0x51, 0x2e, 0x14, 0x4b,
	0x9f, 0xe1, 0x6a, 0x4c, 0x72, 0x82, 0xcf, 0x00, 0x0f, 0x9e, 0x60, 0x0b, 0xea, 0x39, 0xa7, 0x59,
	0x1a, 0xad, 0xa8, 0x7e, 0xde, 0xb2, 0xc6, 0x97, 0xb0, 0x57, 0x38, 0xa6, 0xc7, 0xe8, 0x2a, 0xf8,
	0x67, 0x80, 0x75, 0xc5, 0x62, 0x24, 0x50, 0x5f, 0x51, 0x11, 0x25, 0x91, 0x88, 0xb4, 0x03, 0x48,
	0xae, 0x58, 0x4c, 0xbe, 0x6a, 0x70, 0x90, 0x8a, 0x6c, 0x13, 0x96, 0x1c, 0x3c, 0x06, 0x5b, 0x6c,
	0xd6, 0xc5, 0xc5, 0x1b, 0x5d, 0x47, 0x71, 0x27, 0x9b, 0x35, 0x0d, 0x15, 0x5c, 0xbe, 0xbc, 0xf5,
	0xe4, 0xe5, 0x5b, 0x1f, 0xe1, 0x70, 0x67, 0xa8, 0xb4, 0x6b, 0x41, 0x37, 0xdb, 0x40, 0x2e, 0xe8,
	0x46, 0xda, 0x7a, 0x17, 0x2d, 0xf3, 0xd2, 0x56, 0x55, 0x9c, 0x99, 0x1f, 0x8c, 0xe0, 0x0c, 0x6c,
	0x79, 0x0a, 0x1e, 0x40, 0xfd, 0x62, 0x34, 0xfd, 0x36, 0x1c, 0xf5, 0x2e, 0xfc, 0x67, 0xf8, 0x1c,
	0xbc, 0xf3, 0xde, 0xf0, 0xfc, 0xfb, 0xb0, 0x37, 0x19, 0xcc, 0xc6, 0x93, 0xde, 0x64, 0xec, 0x1b,
	0xe8, 0x81, 0x7b, 0x39, 0x98, 0xcc, 0xc2, 0xc1, 0xf5, 0x97, 0xc1, 0x74, 0xec, 0x9b, 0xdd, 0xbf,
	0x06, 0xb8, 0x52, 0x47, 0x3f, 0xfa, 0xb9, 0xa0, 0x69, 0x82, 0xa7, 0xb0, 0xaf, 0x63, 0x8f, 0x1e,
	0xd9, 0x5d, 0x92, 0x96, 0x4f, 0xaa, 0x1b, 0x71, 0x0a, 0xfb, 0x3a, 0xde, 0xe8, 0x91, 0xdd, 0x5d,
	0x68, 0xf9, 0xa4, 0x9a, 0xfc, 0x2e, 0x38, 0x65, 0xc4, 0xf0, 0x88, 0x54, 0x23, 0xd8, 0x42, 0xf2,
	0x24, 0x81, 0x7d, 0xfb, 0x87, 0xb9, 0x8e, 0xe3, 0x3d, 0xb5, 0xb7, 0xef, 0xff, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x64, 0xb8, 0xe3, 0x5e, 0xc5, 0x03, 0x00, 0x00,
}
